-- Run this in Supabase SQL Editor to update your exercise GIFs!

ALTER TABLE public.exercises ADD COLUMN IF NOT EXISTS gif_url text;
ALTER TABLE public.exercises ADD COLUMN IF NOT EXISTS instructions text;

UPDATE public.exercises SET gif_url = '/gifs/3TZduzM.gif', instructions = 'Step:1 Set up an incline bench at a 45-degree angle. Step:2 Lie down on the bench with your feet flat on the ground. Step:3 Grasp the barbell with an overhand grip, slightly wider than shoulder-width apart. Step:4 Unrack the barbell and lower it slowly towards your chest, keeping your elbows at a 45-degree angle. Step:5 Pause for a moment at the bottom, then push the barbell back up to the starting position. Step:6 Repeat for the desired number of repetitions.' WHERE name = 'Bench Press';
UPDATE public.exercises SET gif_url = '/gifs/3TZduzM.gif', instructions = 'Step:1 Set up an incline bench at a 45-degree angle. Step:2 Lie down on the bench with your feet flat on the ground. Step:3 Grasp the barbell with an overhand grip, slightly wider than shoulder-width apart. Step:4 Unrack the barbell and lower it slowly towards your chest, keeping your elbows at a 45-degree angle. Step:5 Pause for a moment at the bottom, then push the barbell back up to the starting position. Step:6 Repeat for the desired number of repetitions.' WHERE name = 'Incline Bench Press';
UPDATE public.exercises SET gif_url = '/gifs/8eqjhOl.gif', instructions = 'Step:1 Set up an incline bench at a 45-degree angle. Step:2 Sit on the bench with your back against the backrest and feet flat on the ground. Step:3 Hold a dumbbell in each hand with an overhand grip, palms facing inwards. Step:4 Extend your arms straight up above your chest, keeping a slight bend in your elbows. Step:5 Lower the dumbbells slowly towards your shoulders, keeping your elbows close to your body. Step:6 Pause for a moment at the bottom, then press the dumbbells back up to the starting position. Step:7 Repeat for the desired number of repetitions.' WHERE name = 'Dumbbell Bench Press';
UPDATE public.exercises SET gif_url = '/gifs/7saC5zz.gif', instructions = 'Step:1 Adjust the cable machine to a decline position. Step:2 Stand facing away from the machine with your feet shoulder-width apart. Step:3 Hold the handles with your palms facing forward and your arms extended straight out in front of you. Step:4 Keeping a slight bend in your elbows, open your arms out to the sides in a controlled motion. Step:5 Pause for a moment at the fully extended position, then slowly return to the starting position. Step:6 Repeat for the desired number of repetitions.' WHERE name = 'Cable Fly';
UPDATE public.exercises SET gif_url = '/gifs/7I6LNUG.gif', instructions = 'Step:1 Adjust the seat height and footrests to a comfortable position. Step:2 Sit on the machine with your chest against the pad and your feet on the footrests. Step:3 Grasp the handles with an overhand grip, shoulder-width apart. Step:4 Keep your back straight and your core engaged. Step:5 Pull the handles towards your body, squeezing your shoulder blades together. Step:6 Pause for a moment at the peak of the movement. Step:7 Slowly release the handles and return to the starting position. Step:8 Repeat for the desired number of repetitions.' WHERE name = 'Bent Over Row';
UPDATE public.exercises SET gif_url = '/gifs/7F1DVzn.gif', instructions = 'Step:1 Adjust the seat height and position yourself on the machine with your knees under the pads and your feet flat on the ground. Step:2 Grasp the handles with an overhand grip, slightly wider than shoulder-width apart. Step:3 Sit upright with your chest lifted and your shoulders back, maintaining a slight arch in your lower back. Step:4 Engage your lats and pull the handles down towards your chest, squeezing your shoulder blades together. Step:5 Pause for a moment at the bottom of the movement, then slowly release the handles back to the starting position. Step:6 Repeat for the desired number of repetitions.' WHERE name = 'Lat Pulldown';
UPDATE public.exercises SET gif_url = '/gifs/7I6LNUG.gif', instructions = 'Step:1 Adjust the seat height and footrests to a comfortable position. Step:2 Sit on the machine with your chest against the pad and your feet on the footrests. Step:3 Grasp the handles with an overhand grip, shoulder-width apart. Step:4 Keep your back straight and your core engaged. Step:5 Pull the handles towards your body, squeezing your shoulder blades together. Step:6 Pause for a moment at the peak of the movement. Step:7 Slowly release the handles and return to the starting position. Step:8 Repeat for the desired number of repetitions.' WHERE name = 'Seated Cable Row';
UPDATE public.exercises SET gif_url = '/gifs/7zdxRTl.gif', instructions = 'Step:1 Adjust the seat and footplate of the smith machine to a comfortable position. Step:2 Sit on the machine with your back against the backrest and your feet shoulder-width apart on the footplate. Step:3 Grasp the handles or sides of the machine for stability. Step:4 Push the footplate away from you by extending your legs, keeping your back against the backrest. Step:5 Pause for a moment at the fully extended position. Step:6 Slowly bend your knees and lower the footplate back towards you, returning to the starting position. Step:7 Repeat for the desired number of repetitions.' WHERE name = 'Overhead Press';
UPDATE public.exercises SET gif_url = '/gifs/2ORFMoR.gif', instructions = 'Step:1 Adjust the sled machine to a comfortable weight. Step:2 Stand on the sled machine with your toes on the platform and your heels hanging off. Step:3 Hold onto the handles for stability. Step:4 Raise your heels as high as possible by pushing through the balls of your feet. Step:5 Pause for a moment at the top, then slowly lower your heels back down to the starting position. Step:6 Repeat for the desired number of repetitions.' WHERE name = 'Lateral Raise';
UPDATE public.exercises SET gif_url = '/gifs/3eGE2JC.gif', instructions = 'Step:1 Stand with your feet shoulder-width apart, holding a dumbbell in each hand with your palms facing your thighs. Step:2 Keeping your arms straight, exhale and lift the dumbbells in front of you until they are at shoulder level. Step:3 Pause for a moment at the top, then inhale and slowly lower the dumbbells back down to the starting position. Step:4 Repeat for the desired number of repetitions.' WHERE name = 'Front Raise';
UPDATE public.exercises SET gif_url = '/gifs/4dUn2iv.gif', instructions = 'Step:1 Stand up straight with your feet shoulder-width apart and hold a barbell with an underhand grip, hands close together. Step:2 Keep your elbows close to your torso and your upper arms stationary throughout the movement. Step:3 Exhale as you curl the weights while contracting your biceps. Continue to raise the bar until your biceps are fully contracted and the bar is at shoulder level. Step:4 Hold the contracted position for a brief pause as you squeeze your biceps. Step:5 Inhale as you slowly begin to bring the barbell back to the starting position. Step:6 Repeat for the desired number of repetitions.' WHERE name = 'Barbell Curl';
UPDATE public.exercises SET gif_url = '/gifs/6sMAmNv.gif', instructions = 'Step:1 Stand up straight with a dumbbell in each hand, palms facing your body and arms fully extended. Step:2 Keeping your upper arms stationary, exhale and curl the weights while contracting your biceps. Step:3 Continue to raise the dumbbells until your biceps are fully contracted and the dumbbells are at shoulder level. Step:4 Hold the contracted position for a brief pause as you squeeze your biceps. Step:5 Inhale and slowly begin to lower the dumbbells back to the starting position. Step:6 Repeat for the desired number of repetitions.' WHERE name = 'Dumbbell Curl';
UPDATE public.exercises SET gif_url = '/gifs/4dF3maG.gif', instructions = 'Step:1 Sit on a preacher bench with a dumbbell in one hand and your upper arm resting on the pad. Step:2 Hold the dumbbell with a neutral grip (palms facing your body). Step:3 Keeping your upper arm stationary, exhale and curl the dumbbell up towards your shoulder. Step:4 Pause for a moment at the top, squeezing your biceps. Step:5 Inhale and slowly lower the dumbbell back to the starting position. Step:6 Repeat for the desired number of repetitions, then switch arms.' WHERE name = 'Hammer Curl';
UPDATE public.exercises SET gif_url = '/gifs/4dF3maG.gif', instructions = 'Step:1 Sit on a preacher bench with a dumbbell in one hand and your upper arm resting on the pad. Step:2 Hold the dumbbell with a neutral grip (palms facing your body). Step:3 Keeping your upper arm stationary, exhale and curl the dumbbell up towards your shoulder. Step:4 Pause for a moment at the top, squeezing your biceps. Step:5 Inhale and slowly lower the dumbbell back to the starting position. Step:6 Repeat for the desired number of repetitions, then switch arms.' WHERE name = 'Preacher Curl';
UPDATE public.exercises SET gif_url = '/gifs/5uFK1xr.gif', instructions = 'Step:1 Sit on a bench with your back straight and feet flat on the ground. Step:2 Hold a barbell with an overhand grip, hands shoulder-width apart, and raise it overhead. Step:3 Lower the barbell behind your head by bending your elbows, keeping your upper arms close to your head. Step:4 Pause for a moment, then extend your arms to raise the barbell back to the starting position. Step:5 Repeat for the desired number of repetitions.' WHERE name = 'Triceps Pushdown';
UPDATE public.exercises SET gif_url = '/gifs/3TZduzM.gif', instructions = 'Step:1 Set up an incline bench at a 45-degree angle. Step:2 Lie down on the bench with your feet flat on the ground. Step:3 Grasp the barbell with an overhand grip, slightly wider than shoulder-width apart. Step:4 Unrack the barbell and lower it slowly towards your chest, keeping your elbows at a 45-degree angle. Step:5 Pause for a moment at the bottom, then push the barbell back up to the starting position. Step:6 Repeat for the desired number of repetitions.' WHERE name = 'Close Grip Bench Press';
UPDATE public.exercises SET gif_url = '/gifs/5bpPTHv.gif', instructions = 'Step:1 Stand with your feet shoulder-width apart, holding a kettlebell in front of your chest with both hands. Step:2 Lift your left foot off the ground and extend it forward, keeping it parallel to the ground. Step:3 Slowly lower your body down into a squat position, keeping your right foot flat on the ground and your left leg extended. Step:4 Pause for a moment at the bottom of the squat, then push through your right heel to return to the starting position. Step:5 Repeat for the desired number of repetitions, then switch legs.' WHERE name = 'Squat';
UPDATE public.exercises SET gif_url = '/gifs/7zdxRTl.gif', instructions = 'Step:1 Adjust the seat and footplate of the smith machine to a comfortable position. Step:2 Sit on the machine with your back against the backrest and your feet shoulder-width apart on the footplate. Step:3 Grasp the handles or sides of the machine for stability. Step:4 Push the footplate away from you by extending your legs, keeping your back against the backrest. Step:5 Pause for a moment at the fully extended position. Step:6 Slowly bend your knees and lower the footplate back towards you, returning to the starting position. Step:7 Repeat for the desired number of repetitions.' WHERE name = 'Leg Press';
UPDATE public.exercises SET gif_url = '/gifs/3XFdb1Z.gif', instructions = 'Step:1 Attach a cable handle to the lowest setting on a cable machine. Step:2 Stand facing the machine with your feet shoulder-width apart. Step:3 Hold the cable handle with an underhand grip, palms facing up, and arms fully extended. Step:4 Lower your body into a squat position, keeping your back straight and knees behind your toes. Step:5 As you squat down, curl the cable handle towards your shoulders, keeping your elbows close to your sides. Step:6 Pause for a moment at the top of the curl, squeezing your biceps. Step:7 Slowly lower the cable handle back to the starting position, fully extending your arms. Step:8 Repeat for the desired number of repetitions.' WHERE name = 'Leg Curl';
UPDATE public.exercises SET gif_url = '/gifs/7zdxRTl.gif', instructions = 'Step:1 Adjust the seat and footplate of the smith machine to a comfortable position. Step:2 Sit on the machine with your back against the backrest and your feet shoulder-width apart on the footplate. Step:3 Grasp the handles or sides of the machine for stability. Step:4 Push the footplate away from you by extending your legs, keeping your back against the backrest. Step:5 Pause for a moment at the fully extended position. Step:6 Slowly bend your knees and lower the footplate back towards you, returning to the starting position. Step:7 Repeat for the desired number of repetitions.' WHERE name = 'Leg Extension';
UPDATE public.exercises SET gif_url = '/gifs/2ORFMoR.gif', instructions = 'Step:1 Adjust the sled machine to a comfortable weight. Step:2 Stand on the sled machine with your toes on the platform and your heels hanging off. Step:3 Hold onto the handles for stability. Step:4 Raise your heels as high as possible by pushing through the balls of your feet. Step:5 Pause for a moment at the top, then slowly lower your heels back down to the starting position. Step:6 Repeat for the desired number of repetitions.' WHERE name = 'Calf Raise';
UPDATE public.exercises SET gif_url = '/gifs/8xUv4J7.gif', instructions = 'Step:1 Sit on a cable machine with your feet flat on the ground and your knees bent. Step:2 Hold the cable handle with both hands and position it behind your head. Step:3 Engage your abs and slowly curl your upper body forward, bringing your chest towards your knees. Step:4 Pause for a moment at the top, then slowly return to the starting position. Step:5 Repeat for the desired number of repetitions.' WHERE name = 'Crunch';
UPDATE public.exercises SET gif_url = '/gifs/8xUv4J7.gif', instructions = 'Step:1 Sit on a cable machine with your feet flat on the ground and your knees bent. Step:2 Hold the cable handle with both hands and position it behind your head. Step:3 Engage your abs and slowly curl your upper body forward, bringing your chest towards your knees. Step:4 Pause for a moment at the top, then slowly return to the starting position. Step:5 Repeat for the desired number of repetitions.' WHERE name = 'Cable Crunch';
